/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_2_operativos.gui;

/**
 *
 * @author COMPUGAMER
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private javax.swing.JLabel[] bloquesVisuales = new javax.swing.JLabel[100];
    private proyecto_2_operativos.controladores.GestorArchivos gestor;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        gestor = new proyecto_2_operativos.controladores.GestorArchivos(100);
        inicializarDiscoVisual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDiscoVirtual = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 35, 45));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(30, 35, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(40, 45, 55));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 80));

        jButton1.setText("Crear");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Leer");

        jButton3.setText("Actualizar");

        jButton4.setText("Eliminar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario", " ", " " }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(40, 45, 55));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 0));

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(40, 45, 55));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Archivo", "Bloques", "Primer Bloque"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panelDiscoVirtual.setBackground(new java.awt.Color(40, 45, 55));

        javax.swing.GroupLayout panelDiscoVirtualLayout = new javax.swing.GroupLayout(panelDiscoVirtual);
        panelDiscoVirtual.setLayout(panelDiscoVirtualLayout);
        panelDiscoVirtualLayout.setHorizontalGroup(
            panelDiscoVirtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDiscoVirtualLayout.setVerticalGroup(
            panelDiscoVirtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(panelDiscoVirtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDiscoVirtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(40, 45, 55));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel5.setPreferredSize(new java.awt.Dimension(280, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cola de Procesos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Journal");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addComponent(jScrollPane4)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // 1. Generamos un color aleatorio en formato hexadecimal para diferenciar los archivos
        java.util.Random rand = new java.util.Random();
        int r = rand.nextInt(200) + 55; // Colores claros
        int g = rand.nextInt(200) + 55;
        int b = rand.nextInt(200) + 55;
        String colorHex = String.format("#%02x%02x%02x", r, g, b);

        // 2. Simulamos la creacion de un archivo de tamano aleatorio (entre 1 y 10 bloques)
        int tamanoAleatorio = rand.nextInt(10) + 1;
        // Generamos un nombre unico usando los milisegundos actuales
        String nombrePrueba = "doc_" + (System.currentTimeMillis() % 1000) + ".txt";

        // 3. Usamos el gestor para intentar crearlo directamente en la carpeta raiz
        boolean exito = gestor.crearArchivo(gestor.getDirectorioRaiz(), nombrePrueba, tamanoAleatorio, "Administrador", colorHex);

        if (exito) {
            System.out.println("Archivo " + nombrePrueba + " creado (" + tamanoAleatorio + " bloques).");
            
            // 4. Actualizamos la cuadricula visual para ver los bloques ocupados
            actualizarDiscoVisual();
            actualizarTabla(); 
            actualizarArbol(); 
        } else {
            // El documento exige limitar el almacenamiento y evitar crear si no hay espacio
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay " + tamanoAleatorio + " bloques libres en el disco.", "Disco Lleno", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    
    private void inicializarDiscoVisual() {
        // Configuramos el panel para que use una cuadricula de 10 filas por 10 columnas
        panelDiscoVirtual.setLayout(new java.awt.GridLayout(10, 10, 2, 2));

        for (int i = 0; i < 100; i++) {
            // Creamos la etiqueta con el numero del bloque
            bloquesVisuales[i] = new javax.swing.JLabel(String.format("%02d", i), javax.swing.SwingConstants.CENTER);
            
            // Lo hacemos opaco para que se pueda pintar el fondo
            bloquesVisuales[i].setOpaque(true);
            
            // Color por defecto (gris oscuro indicando que esta libre)
            bloquesVisuales[i].setBackground(new java.awt.Color(60, 65, 75));
            bloquesVisuales[i].setForeground(new java.awt.Color(220, 220, 220)); // Texto claro
            
            // Le ponemos un borde para que parezcan celdas individuales
            bloquesVisuales[i].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 35, 45)));
            
            // Agregamos el cuadrito al panel contenedor
            panelDiscoVirtual.add(bloquesVisuales[i]);
        }
        
        // Refrescamos el panel para que los cambios sean visibles
        panelDiscoVirtual.revalidate();
        panelDiscoVirtual.repaint();
    }
    
    // Metodo para actualizar los colores de la cuadricula segun el estado del disco
    public void actualizarDiscoVisual() {
        proyecto_2_operativos.modelos.Bloque[] bloquesDelDisco = gestor.getDisco().getBloques();
        
        for (int i = 0; i < 100; i++) {
            if (bloquesDelDisco[i].isOcupado()) {
                // Si esta ocupado, lo pintamos del color hexadecimal del archivo
                String hex = bloquesDelDisco[i].getColorHex();
                bloquesVisuales[i].setBackground(java.awt.Color.decode(hex));
                // Le pone el nombre del archivo como texto flotante 
                bloquesVisuales[i].setToolTipText(bloquesDelDisco[i].getNombreArchivo());
            } else {
                // Si esta libre vuelve al gris oscuro original
                bloquesVisuales[i].setBackground(new java.awt.Color(60, 65, 75));
                bloquesVisuales[i].setToolTipText("Libre");
            }
        }
        panelDiscoVirtual.repaint();
    }
    
    // Metodo para actualizar el JTable con los archivos creados
    public void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Borramos las filas anteriores para no duplicar
        
        proyecto_2_operativos.modelos.Directorio raiz = gestor.getDirectorioRaiz();
        proyecto_2_operativos.estructuras.ListaEnlazada<proyecto_2_operativos.modelos.Archivo> archivos = raiz.getArchivos();
        
        // Recorremos nuestra lista enlazada propia
        for (int i = 0; i < archivos.getSize(); i++) {
            proyecto_2_operativos.modelos.Archivo arch = archivos.get(i);
            // Agregamos la fila: Nombre, Bloques, Primer Bloque
            modelo.addRow(new Object[]{arch.getNombre(), arch.getTamanoBloques(), arch.getPrimerBloque()});
        }
    }
    
    // Metodo para actualizar el JTree de directorios y archivos
    public void actualizarArbol() {
        proyecto_2_operativos.modelos.Directorio raiz = gestor.getDirectorioRaiz();
        
        // Creamos el nodo principal (La carpeta raiz)
        javax.swing.tree.DefaultMutableTreeNode nodoRaiz = new javax.swing.tree.DefaultMutableTreeNode(raiz.getNombre());
        
        proyecto_2_operativos.estructuras.ListaEnlazada<proyecto_2_operativos.modelos.Archivo> archivos = raiz.getArchivos();
        
        // Agregamos cada archivo como un "hijo" de la carpeta raiz
        for (int i = 0; i < archivos.getSize(); i++) {
            proyecto_2_operativos.modelos.Archivo arch = archivos.get(i);
            String infoNodo = arch.getNombre() + " (" + arch.getTamanoBloques() + " bloques)";
            nodoRaiz.add(new javax.swing.tree.DefaultMutableTreeNode(infoNodo));
        }
        
        // Le aplicamos el nuevo modelo al JTree visual
        javax.swing.tree.DefaultTreeModel modeloArbol = new javax.swing.tree.DefaultTreeModel(nodoRaiz);
        jTree1.setModel(modeloArbol);
        
        // Expandimos la raiz para que se vean los archivos por defecto
        jTree1.expandRow(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel panelDiscoVirtual;
    // End of variables declaration//GEN-END:variables
}
